# FindTBB.cmake — load the real Emscripten oneTBB built by the WASM workflow.
set(_TBB_CONFIG "${CMAKE_PREFIX_PATH}/lib/cmake/TBB/TBBConfig.cmake")
if(NOT EXISTS "${_TBB_CONFIG}")
  message(FATAL_ERROR "The WASM build requires installed oneTBB: ${_TBB_CONFIG}")
endif()

include("${_TBB_CONFIG}")
foreach(_TBB_TARGET IN ITEMS TBB::tbb TBB::tbbmalloc TBB::tbbmalloc_proxy)
  if(TARGET "${_TBB_TARGET}")
    get_target_property(_TBB_IS_IMPORTED "${_TBB_TARGET}" IMPORTED)
    get_target_property(_TBB_IS_GLOBAL "${_TBB_TARGET}" IMPORTED_GLOBAL)
    if(_TBB_IS_IMPORTED AND NOT _TBB_IS_GLOBAL)
      set_property(TARGET "${_TBB_TARGET}" PROPERTY IMPORTED_GLOBAL TRUE)
    endif()
  endif()
endforeach()
set(TBB_FOUND TRUE)
set(TBB_INCLUDE_DIRS "${CMAKE_PREFIX_PATH}/include")
set(TBB_LIBRARIES TBB::tbb)
